### PR TITLE
Feature/pile up app

### PR DESCRIPTION
**Pull request by kmtsui**
Make the pile-up generation application be compatible under the new structure.
Also save the raw Cherenkov hits in output which are missing before.

### CODE REVIEW

**Comment by pdeperio** [comment]
@guiguem any idea about this CI fail?

**Comment by kmtsui** [comment]
> @guiguem any idea about this CI fail?

The error seems to be related to secret setup.
```
Error: The ssh-private-key argument is empty. Maybe the secret has not been configured, or you are using a wrong secret name in your workflow file.
```

**Comment by guiguem** [comment]
I believe the issue is that you are working from your own branch, therefore you cannot use the hyperk/mdt secrets were the ssh key was setup.
you would need to set your own ssh key in your repository or make the branch appear in the hyperk repo?

**Comment by kmtsui** [comment]
I don't have write access in the hyperk/MDT repo. Can you grant me the right?

**Comment by guiguem** [comment]
Sorry, I didn't get notified... Can you check now?

**Comment by kmtsui** [comment]
Move to PR https://github.com/hyperk/MDT/pull/5

**Pull request closed without merging**
